### ISSUE TITLE
Crash on end of training

### ISSUE THREAD

**Issue by msuch** [mmagnuski/exp_CircStim#7]
W najnowszej wersji kodu (ze zwolnioną procedurą przy treningu) złapałem dziwny exception:

Traceback (most recent call last):
  File "/Users/mike/projects/preludium/exp_CircStim/gabcon.py", line 55, in <module>
    present_training(exp=slow, slowdown=s)
  File "/Users/mike/projects/preludium/exp_CircStim/stimutils.py", line 222, in present_training
    textscreen(thistxt)
  File "/Users/mike/projects/preludium/exp_CircStim/stimutils.py", line 347, in textscreen
    win.filp()
AttributeError: Window instance has no attribute 'filp'

Zapisuję tutaj, żeby nie uciekło.

**Comment by mmagnuski** [comment]
Masz widocznie nieaktualną wersję - poprawiłem to typo (`filp` a powinno być `flip` :smile: ) w ...
a nie, faktycznie, wygląda że zapomniałem tego pushnąć, albo mam tylko lokalnie
Dzięki!

**Comment by mmagnuski** [comment]
Ok, nie zrobiłem pusha, już poprawione.
